// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDG2_NvZGwixHFKHDSOna7r3Xwxh65p0mM',
    appId: '1:851738367173:web:c5d83c414143877aae0cac',
    messagingSenderId: '851738367173',
    projectId: 'kafe-ef5c2',
    authDomain: 'kafe-ef5c2.firebaseapp.com',
    storageBucket: 'kafe-ef5c2.firebasestorage.app',
    measurementId: 'G-MZVT8YV8W4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAHGTBgOGrMjnuaRnKW4tPCdqh46Wf1WM',
    appId: '1:851738367173:android:dcc0cdb33aeb264fae0cac',
    messagingSenderId: '851738367173',
    projectId: 'kafe-ef5c2',
    storageBucket: 'kafe-ef5c2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuGBCGNyx_IZ6XiDJv-2gC5I8ro9p4v0I',
    appId: '1:851738367173:ios:522dd4c57a65bb4bae0cac',
    messagingSenderId: '851738367173',
    projectId: 'kafe-ef5c2',
    storageBucket: 'kafe-ef5c2.firebasestorage.app',
    iosBundleId: 'com.example.proje',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuGBCGNyx_IZ6XiDJv-2gC5I8ro9p4v0I',
    appId: '1:851738367173:ios:522dd4c57a65bb4bae0cac',
    messagingSenderId: '851738367173',
    projectId: 'kafe-ef5c2',
    storageBucket: 'kafe-ef5c2.firebasestorage.app',
    iosBundleId: 'com.example.proje',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDG2_NvZGwixHFKHDSOna7r3Xwxh65p0mM',
    appId: '1:851738367173:web:c5002879d011bf28ae0cac',
    messagingSenderId: '851738367173',
    projectId: 'kafe-ef5c2',
    authDomain: 'kafe-ef5c2.firebaseapp.com',
    storageBucket: 'kafe-ef5c2.firebasestorage.app',
    measurementId: 'G-XNBY843GD2',
  );
}
